// <auto-generated />
namespace JoinJoy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addgroupinratingmember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgroupinratingmember));
        
        string IMigrationMetadata.Id
        {
            get { return "202311070921019_add group in ratingmember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
